export enum LanguageCode {
  AF = 'AF', // Afrikaans
  SQ = 'SQ', // Albanian
  AM = 'AM', // Amharic
  AR = 'AR', // Arabic
  HY = 'HY', // Armenian
  AS = 'AS', // Assamese
  AY = 'AY', // Aymara
  AZ = 'AZ', // Azerbaijani
  BM = 'BM', // Bambara
  EU = 'EU', // Basque
  BE = 'BE', // Belarusian
  BN = 'BN', // Bengali
  BHO = 'BHO', // Bhojpuri
  BS = 'BS', // Bosnian
  BG = 'BG', // Bulgarian
  CA = 'CA', // Catalan
  CEB = 'CEB', // Cebuano
  ZH = 'ZH', // Chinese
  CO = 'CO', // Corsican
  HR = 'HR', // Croatian
  CS = 'CS', // Czech
  DA = 'DA', // Danish
  DV = 'DV', // Dhivehi
  DOI = 'DOI', // Dogri
  NL = 'NL', // Dutch
  EN = 'EN', // English
  EO = 'EO', // Esperanto
  ET = 'ET', // Estonian
  EE = 'EE', // Ewe
  FIL = 'FIL', // Filipino (Tagalog)
  FI = 'FI', // Finnish
  FR = 'FR', // French
  FY = 'FY', // Frisian
  GL = 'GL', // Galician
  KA = 'KA', // Georgian
  DE = 'DE', // German
  EL = 'EL', // Greek
  GN = 'GN', // Guarani
  GU = 'GU', // Gujarati
  HT = 'HT', // Haitian Creole
  HA = 'HA', // Hausa
  HAW = 'HAW', // Hawaiian
  HE = 'HE', // Hebrew
  HI = 'HI', // Hindi
  HMN = 'HMN', // Hmong
  HU = 'HU', // Hungarian
  IS = 'IS', // Icelandic
  IG = 'IG', // Igbo
  ILO = 'ILO', // Ilocano
  ID = 'ID', // Indonesian
  GA = 'GA', // Irish
  IT = 'IT', // Italian
  JA = 'JA', // Japanese
  JV = 'JV', // Javanese
  KN = 'KN', // Kannada
  KK = 'KK', // Kazakh
  KM = 'KM', // Khmer
  RW = 'RW', // Kinyarwanda
  GOM = 'GOM', // Konkani
  KO = 'KO', // Korean
  KRI = 'KRI', // Krio
  KU = 'KU', // Kurdish
  CKB = 'CKB', // Kurdish (Sorani)
  KY = 'KY', // Kyrgyz
  LO = 'LO', // Lao
  LA = 'LA', // Latin
  LV = 'LV', // Latvian
  LN = 'LN', // Lingala
  LT = 'LT', // Lithuanian
  LG = 'LG', // Luganda
  LB = 'LB', // Luxembourgish
  MK = 'MK', // Macedonian
  MAI = 'MAI', // Maithili
  MG = 'MG', // Malagasy
  MS = 'MS', // Malay
  ML = 'ML', // Malayalam
  MT = 'MT', // Maltese
  MI = 'MI', // Maori
  MR = 'MR', // Marathi
  LUS = 'LUS', // Mizo
  MN = 'MN', // Mongolian
  MY = 'MY', // Myanmar (Burmese)
  NE = 'NE', // Nepali
  NO = 'NO', // Norwegian
  NY = 'NY', // Nyanja (Chichewa)
  OR = 'OR', // Odia (Oriya)
  OM = 'OM', // Oromo
  PS = 'PS', // Pashto
  FA = 'FA', // Persian
  PL = 'PL', // Polish
  PT = 'PT', // Portuguese
  PA = 'PA', // Punjabi
  QU = 'QU', // Quechua
  RO = 'RO', // Romanian
  RU = 'RU', // Russian
  SM = 'SM', // Samoan
  SA = 'SA', // Sanskrit
  GD = 'GD', // Scots Gaelic
  NSO = 'NSO', // Sepedi
  SR = 'SR', // Serbian
  ST = 'ST', // Sesotho
  SN = 'SN', // Shona
  SD = 'SD', // Sindhi
  SI = 'SI', // Sinhala (Sinhalese)
  SK = 'SK', // Slovak
  SL = 'SL', // Slovenian
  SO = 'SO', // Somali
  ES = 'ES', // Spanish
  SU = 'SU', // Sundanese
  SW = 'SW', // Swahili
  SV = 'SV', // Swedish
  TL = 'TL', // Tagalog (Filipino)
  TG = 'TG', // Tajik
  TA = 'TA', // Tamil
  TT = 'TT', // Tatar
  TE = 'TE', // Telugu
  TH = 'TH', // Thai
  TI = 'TI', // Tigrinya
  TS = 'TS', // Tsonga
  TR = 'TR', // Turkish
  TK = 'TK', // Turkmen
  AK = 'AK', // Twi (Akan)
  UK = 'UK', // Ukrainian
  UR = 'UR', // Urdu
  UG = 'UG', // Uyghur
  UZ = 'UZ', // Uzbek
  VI = 'VI', // Vietnamese
  CY = 'CY', // Welsh
  XH = 'XH', // Xhosa
  YI = 'YI', // Yiddish
  YO = 'YO', // Yoruba
  ZU = 'ZU', // Zulu

  // Languages with about a million native speakers or more that the original list,
  // taken from a translator's catalogue, left out.
  ACE = 'ACE', // Acehnese
  ACH = 'ACH', // Acholi
  AJG = 'AJG', // Adja
  AA = 'AA', // Afar
  ARQ = 'ARQ', // Algerian Arabic
  AWA = 'AWA', // Awadhi
  BFY = 'BFY', // Bagheli
  BGQ = 'BGQ', // Bagri
  BQI = 'BQI', // Bakhtiari
  BAN = 'BAN', // Balinese
  BAL = 'BAL', // Balochi
  BJN = 'BJN', // Banjar
  BCI = 'BCI', // Baoule
  BA = 'BA', // Bashkir
  BAR = 'BAR', // Bavarian
  BEJ = 'BEJ', // Beja
  BEM = 'BEM', // Bemba
  BEW = 'BEW', // Betawi
  BHB = 'BHB', // Bhili
  BIK = 'BIK', // Bikol
  BRX = 'BRX', // Bodo
  PCC = 'PCC', // Bouyei
  BRH = 'BRH', // Brahui
  BUG = 'BUG', // Bugis
  WES = 'WES', // Cameroon Pidgin
  YUE = 'YUE', // Cantonese
  TZM = 'TZM', // Central Atlas Tamazight
  SHU = 'SHU', // Chadian Arabic
  CE = 'CE', // Chechen
  HNE = 'HNE', // Chhattisgarhi
  CTG = 'CTG', // Chittagonian
  CV = 'CV', // Chuvash
  DGA = 'DGA', // Dagaare
  DAG = 'DAG', // Dagbani
  PRS = 'PRS', // Dari
  DHD = 'DHD', // Dhundari
  DIN = 'DIN', // Dinka
  DYU = 'DYU', // Dioula
  RMT = 'RMT', // Domari
  CDO = 'CDO', // Eastern Min
  TAJ = 'TAJ', // Eastern Tamang
  BIN = 'BIN', // Edo
  EFI = 'EFI', // Efik
  ARZ = 'ARZ', // Egyptian Arabic
  EGL = 'EGL', // Emilian
  FON = 'FON', // Fon
  FF = 'FF', // Fula
  GAN = 'GAN', // Gan Chinese
  GBM = 'GBM', // Garhwali
  GRT = 'GRT', // Garo
  GPE = 'GPE', // Ghanaian Pidgin English
  GLK = 'GLK', // Gilaki
  GON = 'GON', // Gondi
  GOR = 'GOR', // Gorontalo
  GUW = 'GUW', // Gun
  AYH = 'AYH', // Hadhrami Arabic
  HAK = 'HAK', // Hakka
  BGC = 'BGC', // Haryanvi
  MEY = 'MEY', // Hassaniya Arabic
  HAZ = 'HAZ', // Hazaragi
  ACW = 'ACW', // Hijazi Arabic
  HIL = 'HIL', // Hiligaynon
  HOC = 'HOC', // Ho
  CZH = 'CZH', // Huizhou Chinese
  IBA = 'IBA', // Iban
  IGL = 'IGL', // Igala
  ACM = 'ACM', // Iraqi Arabic
  TTS = 'TTS', // Isan
  JAM = 'JAM', // Jamaican Patois
  CJY = 'CJY', // Jin Chinese
  QUC = 'QUC', // K'iche'
  KBD = 'KBD', // Kabardian
  KBP = 'KBP', // Kabiye
  KAB = 'KAB', // Kabyle
  KBR = 'KBR', // Kafa
  KMC = 'KMC', // Kam
  KAM = 'KAM', // Kamba
  KR = 'KR', // Kanuri
  PAM = 'PAM', // Kapampangan
  KAI = 'KAI', // Karai-karai
  KRJ = 'KRJ', // Karay-a
  KS = 'KS', // Kashmiri
  KHG = 'KHG', // Khams Tibetan
  KHN = 'KHN', // Khandeshi
  CGG = 'CGG', // Kiga
  KI = 'KI', // Kikuyu
  RN = 'RN', // Kirundi
  KG = 'KG', // Kongo
  KFY = 'KFY', // Kumaoni
  KRU = 'KRU', // Kurukh
  LKI = 'LKI', // Laki
  LMN = 'LMN', // Lambadi
  LAJ = 'LAJ', // Lango
  APC = 'APC', // Levantine Arabic
  AYL = 'AYL', // Libyan Arabic
  LI = 'LI', // Limburgish
  LMO = 'LMO', // Lombard
  NDS = 'NDS', // Low German
  LUA = 'LUA', // Luba-Kasai
  LUO = 'LUO', // Luo
  MAD = 'MAD', // Madurese
  MAG = 'MAG', // Magahi
  MDH = 'MDH', // Maguindanao
  MAK = 'MAK', // Makassar
  VMW = 'VMW', // Makhuwa
  KDE = 'KDE', // Makonde
  MUP = 'MUP', // Malvi
  BTM = 'BTM', // Mandailing Batak
  MNK = 'MNK', // Mandinka
  MWR = 'MWR', // Marwari
  MZN = 'MZN', // Mazanderani
  MNI = 'MNI', // Meitei (Manipuri)
  WRY = 'WRY', // Merwari
  MTR = 'MTR', // Mewari
  WTM = 'WTM', // Mewati
  MIN = 'MIN', // Minangkabau
  ARY = 'ARY', // Moroccan Arabic
  MOS = 'MOS', // Mossi
  UNR = 'UNR', // Mundari
  MTQ = 'MTQ', // Muong
  SCK = 'SCK', // Nagpuri
  NAP = 'NAP', // Neapolitan
  PCM = 'PCM', // Nigerian Pidgin
  NOE = 'NOE', // Nimadi
  KXM = 'KXM', // Northern Khmer
  LRC = 'LRC', // Northern Luri
  MNP = 'MNP', // Northern Min
  ND = 'ND', // Northern Ndebele
  NOD = 'NOD', // Northern Thai (Lanna)
  II = 'II', // Nuosu
  NYN = 'NYN', // Nyankole
  PFL = 'PFL', // Palatinate German
  PAG = 'PAG', // Pangasinan
  PMS = 'PMS', // Piedmontese
  CPX = 'CPX', // Pu-Xian Min
  RAJ = 'RAJ', // Rajasthani
  RHG = 'RHG', // Rohingya
  RGN = 'RGN', // Romagnol
  ROM = 'ROM', // Romani
  KSW = 'KSW', // S'gaw Karen
  AEC = 'AEC', // Saidi Arabic
  SPV = 'SPV', // Sambalpuri
  AYN = 'AYN', // Sanaani Arabic
  SG = 'SG', // Sango
  SAT = 'SAT', // Santali
  SKR = 'SKR', // Saraiki
  SC = 'SC', // Sardinian
  SAS = 'SAS', // Sasak
  SCO = 'SCO', // Scots
  SGW = 'SGW', // Sebat Bet Gurage
  SRR = 'SRR', // Serer
  SHN = 'SHN', // Shan
  SHY = 'SHY', // Shawiya
  SHK = 'SHK', // Shilluk
  SCN = 'SCN', // Sicilian
  SID = 'SID', // Sidamo
  SNK = 'SNK', // Soninke
  AZB = 'AZB', // South Azerbaijani
  SDH = 'SDH', // Southern Kurdish
  LUZ = 'LUZ', // Southern Luri
  NAN = 'NAN', // Southern Min (Hokkien)
  SOU = 'SOU', // Southern Thai
  APD = 'APD', // Sudanese Arabic
  SUK = 'SUK', // Sukuma
  SUS = 'SUS', // Susu
  SS = 'SS', // Swazi
  GSW = 'GSW', // Swiss German (Alemannic)
  SYL = 'SYL', // Sylheti
  ACQ = 'ACQ', // Taizzi-Adeni Arabic
  RIF = 'RIF', // Tarifit
  SHI = 'SHI', // Tashelhit
  TSG = 'TSG', // Tausug
  BO = 'BO', // Tibetan
  BBC = 'BBC', // Toba Batak
  TPI = 'TPI', // Tok Pisin
  TOI = 'TOI', // Tonga
  TSC = 'TSC', // Tswa
  TN = 'TN', // Tswana
  TMH = 'TMH', // Tuareg
  TCY = 'TCY', // Tulu
  TUM = 'TUM', // Tumbuka
  AEB = 'AEB', // Tunisian Arabic
  TYZ = 'TYZ', // Tày
  UMB = 'UMB', // Umbundu
  SXU = 'SXU', // Upper Saxon
  URH = 'URH', // Urhobo
  VE = 'VE', // Venda
  VEC = 'VEC', // Venetian
  WAR = 'WAR', // Waray
  VLS = 'VLS', // West Flemish
  WAL = 'WAL', // Wolaytta
  WO = 'WO', // Wolof
  WUU = 'WUU', // Wu Chinese
  HSN = 'HSN', // Xiang Chinese
  ZZA = 'ZZA', // Zazaki
  ZA = 'ZA', // Zhuang
}
