name: Build and Deploy Angular Frontend to VM

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend to VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App for Production
        run: npm run build -- --configuration production

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create Target Directory on VM (if it doesn't exist)
        run: |
          ssh -o StrictHostKeyChecking=no kuzanoleg@104.154.227.193 "mkdir -p /var/www/almonium-fe"

      - name: Deploy Built Files using rsync
        run: |
          ssh-keyscan -H 104.154.227.193 >> ~/.ssh/known_hosts

          rsync -avz --delete \
            ./dist/almonium-fe/browser/ \
            kuzanoleg@104.154.227.193:/var/www/almonium-fe/

      - name: Deployment Summary
        run: echo "Successfully deployed frontend to VM path /var/www/almonium-fe/"
